import sqlite3
from sqlite3 import Error
import pandas as pd
import time 
#busid = 343
 
def create_connection(db_file,busid):
    """ create a database connection to a SQLite database """
    conn = None
    try:
        conn = sqlite3.connect(db_file)

        cursor = conn.cursor()

        #cursor.execute('select * from Feb2016_01 where ROUTE_ID =:ID', {"ID":busid})
        cursor.execute("SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_01 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_02 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_03 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_04 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_05 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_06 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_07 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_08 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_09 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_10 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_11 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_12 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_13 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_14 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_15 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_16 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_17 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_18 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_19 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_20 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_21 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_22 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_23 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_24 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_25 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_26 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_27 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_28 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Feb2016_29 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_01 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_02 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_03 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_04 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_05 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_06 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_07 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_08 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_09 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_10 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_11 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_12 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_13 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_14 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_15 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_16 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_17 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_18 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_19 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_20 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_21 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_22 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_23 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_24 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_25 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_26 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_27 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_28 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_29 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_30 WHERE ROUTE_ID = :ID union all"+" "+
        "SELECT CIN, CARD_TYP_CD, ROUTE_ID, BUS_ID, OPRTR_ID, RUN_DIR_CD, TRIP_ID, JS_STRT_DT_FK, TAG1_TM, TAG1_TS_NUM, TAG1_TS_NM, TAG1_LAT_VAL, TAG1_LONG_VAL, TAG2_TM, TAG2_TS_NUM, TAG2_TS_NM, TAG2_LAT_VAL, TAG2_LONG_VAL FROM Mar2016_30 WHERE ROUTE_ID = :ID "
        ,{"ID":busid})
        
        
        
        
        values = cursor.fetchall()
        
        name=["CIN","CARD_TYP_CD","ROUTE_ID","BUS_ID","OPRTR_ID","RUN_DIR_CD","TRIP_ID","JS_STRT_DT_FK","TAG1_TM","TAG1_TS_NUM","TAG1_TS_NM","TAG1_LAT_VAL","TAG1_LONG_VAL","TAG2_TM","TAG2_TS_NUM","TAG2_TS_NM","TAG2_LAT_VAL","TAG2_LONG_VAL"]
        values_csv=pd.DataFrame(columns=name,data=values)
        #values_csv.sort_values("")
        values_csv.to_csv("C:\\Users\\bdu\\Desktop\\gzy\\BusBunching\\BusData\\"+str(busid)+".csv")
        print(busid)
        print(values_csv)
        print("--------------------------------")
        print()
        
    except Error as e:
        print(e)
    finally:
        if conn:
            conn.close()
 
 
if __name__ == '__main__':

    start = time.time()

    busids = [326,327,386,387,369,397,399,412]
    for busid in busids:
        create_connection(r"C:\D\Opal2016FebMar\opal4MA.db",busid)
        end = time.time()
        print(end-start)